### PR TITLE
Fix issues

### PR DESCRIPTION
**Pull request by miles-six**
I have been studying this repository for a long time, and whenever I come across a typo, I fix it. 

I discovered 33 typos in a total of 23 files. Then I merged them together.

The code quality is exceptionally high, so sincerely hope my PR can help make this repository more standardized.

### CODE REVIEW

**Review by jonathanpwang — APPROVED** [review]
Thank you for carefully reading the code and helping to improve it!

**Comment by miles-six** [comment]
@jonathanpwang  The workflow fails with some test functions, I don't know why,how can I fix it

**Comment by nyunyunyunyu** [comment]
> @jonathanpwang The workflow fails with some test functions, I don't know why,how can I fix it

@jonathanpwang  It seems that the node secret is incorrect now. Maybe the apikey expired.

**Comment by miles-six** [comment]
> > @jonathanpwang The workflow fails with some test functions, I don't know why,how can I fix it
> 
> @jonathanpwang It seems that the node secret is incorrect now. Maybe the apikey expired.

Is this not my issue, right?

**Comment by nyunyunyunyu** [comment]
> > > @jonathanpwang The workflow fails with some test functions, I don't know why,how can I fix it
> > 
> > 
> > @jonathanpwang It seems that the node secret is incorrect now. Maybe the apikey expired.
> 
> Is this not my issue, right?

Sry for confusion. Yes, that can only be fixed by the admin of this repo.

**Comment by taint160596** [comment]
Thank all

**Pull request merged**
